export const NavbarUser = [
  {
    id: 1,
    name: "Courses",
    path: "",
    visible: "only-user",
    type: "parent",
    hidden: false,
    children: [
      {
        id: 1,
        type: "inner-parent",
        name: "Test 1",
        route: [
          {
            id: 1,
            name: "Test 1 1",
            element: <h1>Test 1 1</h1>,
            path: "/test-1-1",
            visible: "only-user",
            hidden: false,
            children: [],
            type: "route",
          },
          {
            id: 2,
            name: "Test 1 2",
            element: <h1>Test 1 2</h1>,
            path: "/test-1-1",
            visible: "only-user",
            hidden: false,
            children: [],
            type: "route",
          },
        ],
      },
      {
        id: 2,
        name: "Test 2",
        type: "inner-parent",
        route: [
          {
            id: 1,
            name: "Test 121",
            element: <h1>Test 2 1</h1>,
            path: "/test-2-1",
            visible: "only-user",
            hidden: false,
            children: [],
            type: "route",
          },
          {
            id: 2,
            name: "Test 2 2",
            element: <h1>Test 2 2</h1>,
            path: "/test-2-1",
            visible: "only-user",
            hidden: false,
            children: [],
            type: "route",
          },
        ],
      },
    ],
  },
  {
    id: 2,
    name: "Leaderboard",
    element: <h1>Leaderboard</h1>,
    path: "/leaderboard",
    visible: "only-user",
    hidden: false,
    children: [],
    type: "route",
  },
  {
    id: 3,
    name: "Code Bits",
    element: <h1>Code bits</h1>,
    path: "/code-bits",
    visible: "only-user",
    hidden: false,
    children: [],
    type: "route",
  },
  {
    id: 4,
    name: "Discuss",
    element: <h1>Discuss</h1>,
    path: "/discuss",
    visible: "only-user",
    hidden: false,
    children: [],
    type: "route",
  },
  {
    id: 5,
    name: "Blog",
    element: <h1>Blog</h1>,
    path: "/blog",
    visible: "only-user",
    hidden: false,
    children: [],
    type: "route",
  },
];

export const NavbarNewUser = [
  {
    id: 1,
    name: "Courses",
    path: "",
    visible: "only-user",
    type: "parent",
    hidden: false,
    children: [
      {
        id: 1,
        type: "inner-parent",
        name: "Test 1",
        route: [
          {
            id: 1,
            name: "Test 1 1",
            element: <h1>Test 1 1</h1>,
            path: "/test-1-1",
            visible: "only-user",
            hidden: false,
            children: [],
            type: "route",
          },
          {
            id: 2,
            name: "Test 1 2",
            element: <h1>Test 1 2</h1>,
            path: "/test-1-1",
            visible: "only-user",
            hidden: false,
            children: [],
            type: "route",
          },
        ],
      },
      {
        id: 2,
        name: "Test 2",
        type: "inner-parent",
        route: [
          {
            id: 1,
            name: "Test 121",
            element: <h1>Test 2 1</h1>,
            path: "/test-2-1",
            visible: "only-user",
            hidden: false,
            children: [],
            type: "route",
          },
          {
            id: 2,
            name: "Test 2 2",
            element: <h1>Test 2 2</h1>,
            path: "/test-2-1",
            visible: "only-user",
            hidden: false,
            children: [],
            type: "route",
          },
        ],
      },
    ],
  },
  {
    id: 2,
    name: "Leaderboard",
    element: <h1>Leaderboard</h1>,
    path: "/leaderboard",
    visible: "only-user",
    hidden: false,
    children: [],
    type: "route",
  },
  {
    id: 3,
    name: "Code Bits",
    element: <h1>Code bits</h1>,
    path: "/code-bits",
    visible: "only-user",
    hidden: false,
    children: [],
    type: "route",
  },
  {
    id: 4,
    name: "Discuss",
    element: <h1>Discuss</h1>,
    path: "/discuss",
    visible: "only-user",
    hidden: false,
    children: [],
    type: "route",
  },
  {
    id: 5,
    name: "Blog",
    element: <h1>Blog</h1>,
    path: "/blog",
    visible: "only-user",
    hidden: false,
    children: [],
    type: "route",
  },
];
